language: java
install: true
jdk:
- openjdk8
jobs:
  include:
  - stage: build
    if: type IN (push, pull_request)
    install: "./gradlew assemble"
    script: "./gradlew check"
    after_success:
    - bash <(curl -s https://codecov.io/bash) -t c82b7db7-70b1-4264-9b8a-b74c077e974d
  - stage: snapshot
    install: skip
    script: "./gradlew publish -PpublishRepo=jcenterSnapshot -PpublishUsername=$BINTRAY_USER
      -PpublishPassword=$BINTRAY_KEY"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: XqCzLuN+Lc8BpXyRTDXyf2xDfaO1m2elrSvLvn1NSrqfHEw6fZu2bMG+KTPE/dDe7pnZj33/x4tfsRIInv4mKAY4nbc202t0bcEokSUvWK+pJ7r6fl5Gny4i5QKNzY5AbEyt1Xf2fU/cAVVk3t+L1134vhi2PAbqIsCnVKUUp8TVTgKAwPwSc6xrk3QURCi7gS3FZXBY38ZPkdhOyN6URWsbxHuIhKMd+hFhRc8N2D5o7z+iM+7eNKJS5vIrWujgIEsSSUBmsk/OHkONbWbwdnfjO0uyYdJV7bXm7qU3x2VewgOPm0zlBpjzSzhvDCJDTtF4r3VuLbJfL+Q2IxLB9wkZ3Cn8u3XajbtlWy8657+D1Z+PCpLD9EpUzM163vCwmjx/bE3zSPupu23RcOi5w2gySm4qguyv5Z+Cv0Tq+5vmtZhwn0u68DoDrtpwSbfn/mdQaTvC4gV45nKs2DIRBx2awsLSzJycARdhhea29aFRXZsXH34rQUFyaLGVfw2PO/LJIxw4C/FP87p/TZAhW2z+8r2MLAjgvRMxhj9+B4YeHV6uMn3ww5dSMhIau5boGl6knY7WUCg1uWbLPTPCDwFzTEfn783AGwtIdcA+w1NYZ7nu4uaPm4xIakyFcvWMUAoSYj0oCkBnq61/IGE2368HM25RoTh5lWcCwpWlz60=
  - secure: bWSW8xwrZorLm71AlzqhnoXwPtANZUdJs1dbxLPBy9mJc+yfRFVianmjO/WY4IYuiro/+vYwpK8aDBhe46I2WC6RbSBWWSWd//EsbGmnn/ElxKnQkIQ+Zz7o/ME6zFJ5/EjafnIXHrgCDL3AGD/0oCGvhbOhHN2KgPGBnPCJXvHGt3Xk5AiWpIy2rw0xO6lO7lI7RanmlkR5vVeW1a6qxyG+nS/UyQHbv1jOi1FQ1JvdYTmmlztNTyj8xaA2mnKu3Zn1fHTQ0fbFeQaKGfWqD6C/vQgiX6L708Sg3vXTfYvx2EyoxM7TfE/ncK59NXot7tVd6F765F/Mdk+2vlcQjeXAlMKKebo2hQoHM1BMab0uNWp1mdM+FVWMcpnaIRPMYysX0iHlMQx0aCmOSuDlxMwa0UrqQqMJmOSDsftC9YOa97+ixjTBk6jHVtVcyKPZdy4SeWG55Dm7NQ+1UrOb6S8iu1xCxKqJKabOBg59uOkVD3K9mDBbgfdRVeeOSfFWRcc+CqNcktRSCojH+Tm+whZGKNzE1EgJLoyQI7LJoGartJXZfi9zXbuHFxvsaEnXFh7U/XfXiheharlnJoS49RxrC5Ukww7xPTv0HRzylTqa2HIO75MCCaU9aezch2vU9ExJ2JwulL9pVgcjl/gLXwsqBlSoJdoVmHfC4WmYjBE=
